package com.example.ui.theme

/**
 * Simple localization system. Holds all UI strings in Persian and English.
 * Accessed via [LocalStrings] CompositionLocal, provided by MyApplicationTheme
 * based on the user's language preference.
 */
data class AppStrings(
    // Chat list
    val connected: String,
    val updating: String,
    val allChats: String,
    val searchChats: String,
    val noMessagesYet: String,
    val lightMode: String,
    val darkMode: String,
    val newGroup: String,
    val savedMessages: String,
    // Contacts
    val contacts: String,
    val searchContacts: String,
    val newChannel: String,
    val addContact: String,
    val addContactHint: String,
    val noContactsMatch: String,
    val noContactsRegistered: String,
    val allowContacts: String,
    val allowContactsHint: String,
    // Settings
    val settings: String,
    val account: String,
    val chatSettings: String,
    val privacySecurity: String,
    val dataStorage: String,
    val chatFolders: String,
    val devices: String,
    val powerSaving: String,
    val language: String,
    val help: String,
    val askQuestion: String,
    val logOut: String,
    // Profile
    val profile: String,
    val setPhoto: String,
    val editInfo: String,
    val online: String,
    val lastSeenRecently: String,
    val mobile: String,
    val bio: String,
    val username: String,
    val birthday: String,
    val noPostsYet: String,
    // Chat detail
    val message: String,
    val mute: String,
    val unmute: String,
    val call: String,
    // Common
    val cancel: String,
    val create: String,
    val add: String,
    val retry: String,
    val close: String,
    val name: String,
    val description: String,
    val descriptionOptional: String,
    // Setup
    val setUpProfile: String,
    val setUpProfileHint: String,
    val nameHint: String,
    val usernameHint: String,
    val continueBtn: String,
    val photoOptional: String,
    // Chat settings
    val messageTextSize: String,
    val messageCorners: String,
    val changeWallpaper: String,
    val changeNameColor: String,
    val switchToDayMode: String,
    val switchToNightMode: String,
    val browseThemes: String,
    val doubleTapReaction: String,
    val quickReaction: String,
    // Privacy
    val lastSeenOnline: String,
    val phoneNumber: String,
    val forwardedMessages: String,
    val groupsChannels: String,
    val hidePhoneNumber: String,
    val hidePhoneHint: String,
    // Data
    val diskNetworkUsage: String,
    val storageUsage: String,
    val dataUsage: String,
    val autoMediaDownload: String,
    val whenMobileData: String,
    val whenWifi: String,
    val whenRoaming: String,
    val resetAutoDownload: String,
    val saveToGallery: String,
    val privateChats: String,
    val groups: String,
    val channels: String,
    val clearCache: String,
    // Folders
    val createFoldersHint: String,
    val recommendedFolders: String,
    val yourFolders: String,
    val createNewFolder: String,
    val showFolderTags: String,
    // Devices
    val thisDevice: String,
    val activeSessions: String,
    val logoutAllDevices: String,
    val logoutAllConfirm: String,
    val logoutAllMsg: String,
    // Power
    val enablePowerSaving: String,
    val powerSavingHint: String,
    val lowerMediaQuality: String,
    val disableAnimations: String,
    val disableAutoPlay: String,
    // Language
    val persian: String,
    val english: String,
    val appLanguage: String,
    // Login
    val enterPhoneNumber: String,
    val enterCode: String,
    val sendCode: String,
    val confirmSignIn: String,
    val resendCode: String
)

val EnglishStrings = AppStrings(
    connected = "connected",
    updating = "Updating...",
    allChats = "All Chats",
    searchChats = "Search chats...",
    noMessagesYet = "No messages yet",
    lightMode = "Light Mode",
    darkMode = "Dark Mode",
    newGroup = "New Group",
    savedMessages = "Saved Messages",
    contacts = "Contacts",
    searchContacts = "Search Contacts",
    newChannel = "New Channel",
    addContact = "Add Contact",
    addContactHint = "Enter phone number or @username",
    noContactsMatch = "No contacts match",
    noContactsRegistered = "None of your device contacts are on 7eve9Chat yet. Tap + to invite someone by username or phone.",
    allowContacts = "Allow Contacts",
    allowContactsHint = "Allow access to your contacts to see who's on 7eve9Chat",
    settings = "Settings",
    account = "Account",
    chatSettings = "Chat Settings",
    privacySecurity = "Privacy & Security",
    dataStorage = "Data and Storage",
    chatFolders = "Chat Folders",
    devices = "Devices",
    powerSaving = "Power Saving",
    language = "Language",
    help = "Help",
    askQuestion = "Ask a Question",
    logOut = "Log Out",
    profile = "Profile",
    setPhoto = "Set Photo",
    editInfo = "Edit Info",
    online = "online",
    lastSeenRecently = "last seen recently",
    mobile = "Mobile",
    bio = "Bio",
    username = "Username",
    birthday = "Birthday",
    noPostsYet = "No posts yet...",
    message = "Message",
    mute = "Mute",
    unmute = "Unmute",
    call = "Call",
    cancel = "Cancel",
    create = "Create",
    add = "Add",
    retry = "Retry",
    close = "Close",
    name = "Name",
    description = "Description",
    descriptionOptional = "Description (optional)",
    setUpProfile = "Set Up Your Profile",
    setUpProfileHint = "Enter your name and choose a username so others can find you on 7eve9Chat.",
    nameHint = "Name",
    usernameHint = "Username",
    continueBtn = "Continue",
    photoOptional = "Photo (optional)",
    messageTextSize = "Message text size",
    messageCorners = "Message corners",
    changeWallpaper = "Change Chat Wallpaper",
    changeNameColor = "Change Name Color",
    switchToDayMode = "Switch to Day Mode",
    switchToNightMode = "Switch to Night Mode",
    browseThemes = "Browse Themes",
    doubleTapReaction = "Double-tap Reaction",
    quickReaction = "Quick Reaction",
    lastSeenOnline = "Last Seen & Online",
    phoneNumber = "Phone Number",
    forwardedMessages = "Forwarded Messages",
    groupsChannels = "Groups & Channels",
    hidePhoneNumber = "Hide My Phone Number",
    hidePhoneHint = "Other users won't see your phone on your profile",
    diskNetworkUsage = "Disk and network usage",
    storageUsage = "Storage Usage",
    dataUsage = "Data Usage",
    autoMediaDownload = "Automatic media download",
    whenMobileData = "When using mobile data",
    whenWifi = "When connected to Wi-Fi",
    whenRoaming = "When roaming",
    resetAutoDownload = "Reset Auto-Download Settings",
    saveToGallery = "Save to Gallery",
    privateChats = "Private Chats",
    groups = "Groups",
    channels = "Channels",
    clearCache = "Clear Cache",
    createFoldersHint = "Create folders for different groups of chats and quickly switch between them.",
    recommendedFolders = "Recommended Folders",
    yourFolders = "Your Folders",
    createNewFolder = "Create New Folder",
    showFolderTags = "Show Folder Tags",
    thisDevice = "This Device",
    activeSessions = "Active Sessions",
    logoutAllDevices = "Log Out All Other Devices",
    logoutAllConfirm = "Log out all other devices?",
    logoutAllMsg = "This will end all other active sessions on your account. You'll stay logged in on this device.",
    enablePowerSaving = "Enable Power Saving",
    powerSavingHint = "Reduces background activity to extend battery life",
    lowerMediaQuality = "Lower Media Quality",
    disableAnimations = "Disable Animations",
    disableAutoPlay = "Disable Auto-Play",
    persian = "فارسی",
    english = "English",
    appLanguage = "App Language",
    enterPhoneNumber = "Enter your phone number",
    enterCode = "Enter Code",
    sendCode = "Send Code",
    confirmSignIn = "Confirm & Sign In",
    resendCode = "Resend code"
)

val PersianStrings = AppStrings(
    connected = "متصل",
    updating = "در حال بروزرسانی...",
    allChats = "همه چت‌ها",
    searchChats = "جستجوی چت‌ها...",
    noMessagesYet = "پیامی وجود ندارد",
    lightMode = "حالت روشن",
    darkMode = "حالت تاریک",
    newGroup = "گروه جدید",
    savedMessages = "پیام‌های ذخیره شده",
    contacts = "مخاطبین",
    searchContacts = "جستجوی مخاطبین",
    newChannel = "کانال جدید",
    addContact = "افزودن مخاطب",
    addContactHint = "شماره تلفن یا @نام کاربری وارد کنید",
    noContactsMatch = "مخاطبی مطابق با",
    noContactsRegistered = "هیچ‌یک از مخاطبین گوشی شما هنوز در 7eve9Chat ثبت‌نام نکرده‌اند. برای دعوت روی + بزنید.",
    allowContacts = "اجازه دسترسی به مخاطبین",
    allowContactsHint = "برای دیدن چه کسانی در 7eve9Chat هستند، به مخاطبین گوشی دسترسی دهید",
    settings = "تنظیمات",
    account = "حساب کاربری",
    chatSettings = "تنظیمات چت",
    privacySecurity = "حریم خصوصی و امنیت",
    dataStorage = "داده و ذخیره‌سازی",
    chatFolders = "پوشه‌های چت",
    devices = "دستگاه‌ها",
    powerSaving = "ذخیره انرژی",
    language = "زبان",
    help = "راهنما",
    askQuestion = "سوال بپرسید",
    logOut = "خروج",
    profile = "پروفایل",
    setPhoto = "تنظیم عکس",
    editInfo = "ویرایش اطلاعات",
    online = "آنلاین",
    lastSeenRecently = "اخیراً آنلاین بوده",
    mobile = "موبایل",
    bio = "بیوگرافی",
    username = "نام کاربری",
    birthday = "تاریخ تولد",
    noPostsYet = "پستی وجود ندارد...",
    message = "پیام",
    mute = "بی‌صدا",
    unmute = "باصدا",
    call = "تماس",
    cancel = "انصراف",
    create = "ایجاد",
    add = "افزودن",
    retry = "تلاش مجدد",
    close = "بستن",
    name = "نام",
    description = "توضیحات",
    descriptionOptional = "توضیحات (اختیاری)",
    setUpProfile = "پروفایل خود را تنظیم کنید",
    setUpProfileHint = "نام و نام کاربری خود را وارد کنید تا دیگران شما را در 7eve9Chat پیدا کنند.",
    nameHint = "نام",
    usernameHint = "نام کاربری",
    continueBtn = "ادامه",
    photoOptional = "عکس (اختیاری)",
    messageTextSize = "اندازه متن پیام",
    messageCorners = "گوشه‌های پیام",
    changeWallpaper = "تغییر پس‌زمینه چت",
    changeNameColor = "تغییر رنگ نام",
    switchToDayMode = "تغییر به حالت روز",
    switchToNightMode = "تغییر به حالت شب",
    browseThemes = "مرور تم‌ها",
    doubleTapReaction = "واکنش با دابل‌تپ",
    quickReaction = "واکنش سریع",
    lastSeenOnline = "آخرین بازدید و آنلاین",
    phoneNumber = "شماره تلفن",
    forwardedMessages = "پیام‌های فوروارد شده",
    groupsChannels = "گروه‌ها و کانال‌ها",
    hidePhoneNumber = "پنهان کردن شماره تلفن",
    hidePhoneHint = "کاربران دیگر شماره تلفن شما را در پروفایل نمی‌بینند",
    diskNetworkUsage = "استفاده از دیسک و شبکه",
    storageUsage = "استفاده از حافظه",
    dataUsage = "استفاده از داده",
    autoMediaDownload = "دانلود خودکار رسانه",
    whenMobileData = "هنگام استفاده از داده موبایل",
    whenWifi = "هنگام اتصال به وای‌فای",
    whenRoaming = "هنگام رومینگ",
    resetAutoDownload = "بازنشانی تنظیمات دانلود خودکار",
    saveToGallery = "ذخیره در گالری",
    privateChats = "چت‌های خصوصی",
    groups = "گروه‌ها",
    channels = "کانال‌ها",
    clearCache = "پاک کردن حافظه پنهان",
    createFoldersHint = "برای دسته‌بندی چت‌ها پوشه بسازید و سریع بین آن‌ها جابجا شوید.",
    recommendedFolders = "پوشه‌های پیشنهادی",
    yourFolders = "پوشه‌های شما",
    createNewFolder = "ایجاد پوشه جدید",
    showFolderTags = "نمایش برچسب پوشه‌ها",
    thisDevice = "این دستگاه",
    activeSessions = "نشست‌های فعال",
    logoutAllDevices = "خروج از همه دستگاه‌ها",
    logoutAllConfirm = "از همه دستگاه‌های دیگر خارج شوید؟",
    logoutAllMsg = "این کار تمام نشست‌های فعال دیگر را پایان می‌دهد. شما در این دستگاه وارد می‌مانید.",
    enablePowerSaving = "فعال‌سازی ذخیره انرژی",
    powerSavingHint = "فعالیت پس‌زمینه را کاهش می‌دهد تا باتری بیشتر دوام بیاورد",
    lowerMediaQuality = "کاهش کیفیت رسانه",
    disableAnimations = "غیرفعال‌سازی انیمیشن‌ها",
    disableAutoPlay = "غیرفعال‌سازی پخش خودکار",
    persian = "فارسی",
    english = "English",
    appLanguage = "زبان برنامه",
    enterPhoneNumber = "شماره تلفن خود را وارد کنید",
    enterCode = "کد را وارد کنید",
    sendCode = "ارسال کد",
    confirmSignIn = "تأیید و ورود",
    resendCode = "ارسال مجدد کد"
)

fun stringsForLanguage(lang: String): AppStrings = when (lang) {
    "fa" -> PersianStrings
    else -> EnglishStrings
}
